apiVersion: v1
kind: Service
metadata:
  name: cli-regulatory-department
  labels:
    app: cli-regulatory-department
spec:
  type: ClusterIP
  selector:
    app: cli-regulatory-department
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-regulatory-department
  labels:
    app: cli-regulatory-department
spec:
  selector:
    matchLabels:
      app: cli-regulatory-department
  template:
    metadata:
      labels:
        app: cli-regulatory-department
    spec:
      containers:
        - name: cli-regulatory-department
          image: cli
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: regulatory-department-cli-env-file
          - secretRef:
              name: regulatory-department-cli-secret-file
          tty: true
          workingDir: /tmp/hyperledger/chaincode
          volumeMounts:
            - mountPath: /tmp/hyperledger/regulatory-department/admin
              name: regulatory-department-admin-mount
            - mountPath: /tmp/hyperledger/regulatory-department/peer1
              name: regulatory-department-peer1-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-mount
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3
      volumes:
        - name: regulatory-department-peer1-mount
          hostPath:
            path: /hyperledger/regulatory-department/peer1
        - name: regulatory-department-admin-mount
          hostPath:
            path: /hyperledger/regulatory-department/admin
        - name: shared-mount
          hostPath:
            path: /hyperledger/shared
        - name: docker-mount
          hostPath:
            path: /var/run/
      initContainers:
        - name: wait-mongo
          image: busybox
          command: ['sh', '-c', 'until nslookup $(DB_HOST); do echo waiting for $(DB_HOST); sleep 2; done;']
          envFrom:
          - configMapRef:
              name: regulatory-department-cli-env-file 
